name = "F# Signature"
code_fence_block_name = "fsharp"
grammar = "fsharp_signature"
path_suffixes = ["fsi"]
line_comments = ["// ", "/// "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
