id = "fsharp"
name = "F#"
description = "F# language support for Zed"
version = "0.0.12"
schema_version = 1
authors = ["Nathan Collins <me@nathancollins.dev>"]
repository = "https://github.com/nathanjcollins/zed-fsharp"

[settings]
fsac_custom_path = { type = "string", optional = true, description = "Custom path to fsautocomplete binary" }
fsac_custom_arguments = { type = "array", items = "string", default = [], description = "Additional arguments for fsautocomplete" }

[language_servers.fsautocomplete]
name = "fsautocomplete"
languages = ["FSharp", "F# Signature"]

[grammars.fsharp]
repository = "https://github.com/MangelMaxime/tree-sitter-fsharp"
commit = "913bc9e78c6cb66642f49c794579aecd9a36868c"

[grammars.fsharp_signature]
repository = "https://github.com/MangelMaxime/tree-sitter-fsharp"
commit = "913bc9e78c6cb66642f49c794579aecd9a36868c"
path = "signature"

[[capabilities]]
kind = "process:exec"
command = "dotnet"
args = ["*"]
